/* Production yield analysis (4mQ.6) */

WITH MT00_CNT (OL_DATE, OL_LID, CNT) AS (
 SELECT DATE(OL_TSEND), OL_LID, COUNT(ML_MLID)
  FROM MATERIAL_LOG, OPERATION_LOG
  WHERE ML_LID=OL_LID AND ML_OLID_DST=OL_OLID 
    AND ML_MTYPE = 'MT00'
    AND OL_TSBEGIN>=TIMESTAMP'[DATE] 00:00:00' 
    AND OL_TSEND<TIMESTAMP'[DATE] 00:00:00' + INTERVAL '1 DAY' 
  GROUP BY DATE(OL_TSEND), OL_LID
),
MT09_CNT (OL_DATE, OL_LID, CNT) AS (
  SELECT DATE(OL_TSEND), OL_LID, COUNT(ML_MLID)
  FROM MATERIAL_LOG, OPERATION_LOG
  WHERE ML_LID=OL_LID AND ML_OLID_SRC=OL_OLID 
    AND ML_MTYPE = 'MT09'
    AND OL_TSBEGIN>=TIMESTAMP'[DATE] 00:00:00'
    AND OL_TSEND<TIMESTAMP'[DATE] 00:00:00' + INTERVAL '1 DAY'
  GROUP BY DATE(OL_TSEND), OL_LID
)
SELECT M9.OL_DATE, M9.OL_LID, M9.CNT*(6.0*24.0*48.0)/M0.CNT  AS YIELD
FROM MT00_CNT M0, MT09_CNT M9
WHERE M0.OL_DATE=M9.OL_DATE AND M0.OL_LID=M9.OL_LID
;
