/* Equipment availability analysis (4mQ.2) */

SELECT DATE_TRUNC('DAY', EL_TS), AVG(ACTIVE_TIME/TOTAL_TIME)
FROM (
  SELECT E_LID, DATE_TRUNC('HOUR', EL_TS) AS EL_TS, E_EID, E_ENAME, 
         COUNT(*) AS ACTIVE_TIME, 3600.0 AS TOTAL_TIME 
  FROM EQUIPMENT_LOG, EQUIPMENT
  WHERE EL_EID = E_EID AND EL_LID = E_LID 
    AND EL_TS BETWEEN DATE'[DATE]' AND DATE'[DATE]' + INTERVAL '1 MONTH'  
    AND EL_SENSOR = 'STATUS' AND EL_READING = 1 
  GROUP BY E_LID, DATE_TRUNC('HOUR', EL_TS), E_EID, E_ENAME
) A 
GROUP BY DATE_TRUNC('DAY',EL_TS) 
ORDER BY 1
;
