/* Quality test query (4mQ.4) */

WITH RECURSIVE R(LID, ML_MLID1,
                 ML_MLID2, ML_MTYPE2, ML_OLID_SRC2,
                 OL_TSBEGIN2, OL_EID2) AS (
  SELECT ML_LID, ML_MLID,
         ML_MLID, ML_MTYPE, ML_OLID_SRC,
         OL_TSBEGIN, OL_EID
  FROM MATERIAL_LOG, OPERATION_LOG
  WHERE ML_LID=OL_LID AND  ML_OLID_SRC=OL_OLID
    AND OL_TSEND BETWEEN DATE'[DATE]' AND DATE'[DATE]' + INTERVAL '1 DAY'
    AND ML_MTYPE='MT09'
  UNION ALL
  SELECT R.LID, R.ML_MLID1,
         ML.ML_MLID, ML.ML_MTYPE, ML.ML_OLID_SRC,
         OL.OL_TSBEGIN, OL.OL_EID
  FROM R, MATERIAL_LOG ML, OPERATION_LOG OL
  WHERE R.LID=ML.ML_LID AND R.ML_OLID_SRC2=ML.ML_OLID_DST
    AND ML.ML_LID=OL.OL_LID AND ML.ML_OLID_SRC=OL.OL_OLID
    AND ML.ML_MTYPE IN ('MT04', 'MT05', 'MT06', 'MT07', 'MT08')
)
SELECT R.LID, R.ML_MLID1 AS MT09_MLID, R.ML_MLID2 AS MT04_MLID
FROM R, MATERIAL_LOG ML, OPERATION_LOG OL, EQUIPMENT_LOG EL
WHERE R.LID=ML.ML_LID AND R.ML_MLID2=ML.ML_MLID
  AND R.LID=OL.OL_LID AND R.ML_OLID_SRC2=OL.OL_OLID
  AND R.OL_EID2=EL.EL_EID AND R.LID=EL.EL_LID AND R.OL_TSBEGIN2=EL.EL_TS
  AND R.ML_MTYPE2='MT04' AND EL.EL_SENSOR='PRESSURE'
  AND NOT (ML.ML_WEIGHT BETWEEN 593.0 AND 607.0 AND ML.ML_DIMENSIONX BETWEEN 9.9 AND 10.1
           AND ML.ML_DIMENSIONY BETWEEN 4.9 AND 5.1 AND ML.ML_DIMENSIONZ BETWEEN 4.9 AND 5.1
           AND ML.ML_SHAPESCORE >= 0.98 AND ML.ML_TEMPERATURE BETWEEN 5.0 AND 35.0
           AND EL.EL_READING BETWEEN 10 AND 20)
;
