/* Production amount analysis (4mQ.1) */

SELECT OL_LID, TRUNC(OL_TSEND, 'HH'), ML_MTYPE, COUNT(*)
FROM OPERATION_LOG, "PROCEDURE", MATERIAL_LOG
WHERE OL_PID=P_PID AND OL_LID=ML_LID AND OL_OLID=ML_OLID_SRC
  AND OL_TSEND >= (SELECT MAX(OL_TSEND) - 1 DAY
                    FROM OPERATION_LOG, "PROCEDURE"
                    WHERE OL_PID=P_PID
                      AND P_PNAME='PROCEDURE000008 (STORAGING)')
  AND P_PNAME IN ('PROCEDURE000003 (BOXING)', 'PROCEDURE000005 (PACKING)',
                  'PROCEDURE000007 (PALLETIZING)', 'PROCEDURE000008 (STORAGING)')
GROUP BY OL_LID, TRUNC(OL_TSEND, 'HH'), ML_MTYPE
ORDER BY 1, 2, 3
;
