/* Equipment availability analysis (4mQ.2) */

-- [DATE] value: 2022-04-25 (default)
--               2022-04-05 (for 40 production days)

SELECT TRUNC(EL_TS, 'DD'), AVG(ACTIVE_TIME/TOTAL_TIME)
FROM (
  SELECT E_LID, TRUNC(EL_TS, 'HH') AS EL_TS, E_EID, E_ENAME,
         COUNT(*) AS ACTIVE_TIME, 3600.0 AS TOTAL_TIME
  FROM EQUIPMENT_LOG, EQUIPMENT
  WHERE EL_EID = E_EID AND EL_LID = E_LID
    AND EL_TS BETWEEN DATE'[DATE]' AND DATE'[DATE]' + 1 MONTH
    AND EL_SENSOR = 'STATUS' AND EL_READING = 1
  GROUP BY E_LID, TRUNC(EL_TS, 'HH'), E_EID, E_ENAME
) A
GROUP BY TRUNC(EL_TS, 'DD')
ORDER BY 1
;
