/* Production yield analysis (4mQ.6) */

-- [TIMESTAMP] value: 2022-07-03 00:00:00 (default)
--                    2022-05-03 00:00:00 (for 40 production days)

WITH MT00_CNT (OL_DATE, OL_LID, CNT) AS (
 SELECT TRUNC(OL_TSEND, 'DD'), OL_LID, COUNT(ML_MLID)
  FROM MATERIAL_LOG, OPERATION_LOG
  WHERE ML_LID=OL_LID AND ML_OLID_DST=OL_OLID
    AND ML_MTYPE = 'MT00'
    AND OL_TSBEGIN>=TIMESTAMP'[TIMESTAMP]'
    AND OL_TSEND<TIMESTAMP'[TIMESTAMP]' + 1 DAY
  GROUP BY TRUNC(OL_TSEND,'DD'), OL_LID
),
MT09_CNT (OL_DATE, OL_LID, CNT) AS (
  SELECT TRUNC(OL_TSEND, 'DD'), OL_LID, COUNT(ML_MLID)
  FROM MATERIAL_LOG, OPERATION_LOG
  WHERE ML_LID=OL_LID AND ML_OLID_SRC=OL_OLID
    AND ML_MTYPE = 'MT09'
    AND OL_TSBEGIN>=TIMESTAMP'[TIMESTAMP]'
    AND OL_TSEND<TIMESTAMP'[TIMESTAMP]' + 1 DAY
  GROUP BY TRUNC(OL_TSEND, 'DD'), OL_LID
)
SELECT M9.OL_DATE, M9.OL_LID, M9.CNT*(6.0*24.0*48.0)/M0.CNT  AS YIELD
FROM MT00_CNT M0, MT09_CNT M9
WHERE M0.OL_DATE=M9.OL_DATE AND M0.OL_LID=M9.OL_LID
;
