/* WORKER */

CREATE TABLE WORKER (
  W_WID     INTEGER,
  W_LID     INTEGER,
  W_WNAME   VARCHAR(128),
  W_COMMENT VARCHAR(128),
  PRIMARY KEY (W_WID, W_WNAME)
);

CREATE INDEX WK_BTREE1 ON WORKER (
  W_WNAME
);

/* EQUIPMENT */

CREATE TABLE EQUIPMENT (
  E_EID     INTEGER,
  E_LID     INTEGER,
  E_ENAME   VARCHAR(64),
  E_COMMENT VARCHAR(128),
  PRIMARY KEY (E_EID, E_LID)
);

CREATE INDEX EQ_BTREE1 ON EQUIPMENT USING BTREE (
  E_ENAME
);

/* PROCEDURE */

CREATE TABLE PROCEDURE (
  P_PID     INTEGER,
  P_PNAME   VARCHAR(128),
  P_COMMENT VARCHAR(128),
  PRIMARY KEY (P_PID)
);

CREATE INDEX PR_BTREE1 ON PROCEDURE USING BTREE (
  P_PNAME
);

/* OPERATION_LOG */

CREATE TABLE OPERATION_LOG (
  OL_OLID      INTEGER,
  OL_LID       INTEGER,
  OL_WID       INTEGER,
  OL_EID       INTEGER,
  OL_PID       INTEGER,
  OL_TSBEGIN   TIMESTAMP,
  OL_TSEND     TIMESTAMP,
  OL_COMMENT   VARCHAR(128),
  PRIMARY KEY (OL_OLID, OL_LID)
);

CREATE INDEX OLOG_BTREE1 ON OPERATION_LOG USING BTREE (
  OL_OLID,
  OL_LID,
  OL_PID,
  OL_TSEND
);

CREATE INDEX OLOG_BTREE2 ON OPERATION_LOG USING BTREE (
  OL_TSBEGIN,
  OL_OLID,
  OL_LID
);

CREATE INDEX OLOG_BTREE3 ON OPERATION_LOG USING BTREE (
  OL_TSEND,
  OL_OLID,
  OL_LID
);

CREATE INDEX OLOG_BTREE4 ON OPERATION_LOG USING BTREE (
  OL_LID,
  OL_EID
);

CREATE INDEX OLOG_BRIN1 ON OPERATION_LOG USING BRIN (
  OL_OLID
);

CREATE INDEX OLOG_BRIN2 ON OPERATION_LOG USING BRIN (
  OL_TSBEGIN
);

CREATE INDEX OLOG_BRIN3 ON OPERATION_LOG USING BRIN (
  OL_TSEND
);

 
/* MATERIAL LOG */

CREATE TABLE MATERIAL_LOG (
  ML_MLID        INTEGER,
  ML_LID         INTEGER,
  ML_MTYPE       VARCHAR(32),
  ML_OLID_SRC    INTEGER,
  ML_OLID_DST    INTEGER,
  ML_SERIAL      VARCHAR(38),
  ML_WEIGHT      DOUBLE PRECISION,
  ML_DIMENSIONX  DOUBLE PRECISION,
  ML_DIMENSIONY  DOUBLE PRECISION,
  ML_DIMENSIONZ  DOUBLE PRECISION,
  ML_SHAPESCORE  DOUBLE PRECISION,
  ML_TEMPERATURE DOUBLE PRECISION,
  ML_COMMENT  VARCHAR(128),
  PRIMARY KEY (ML_MLID, ML_LID)
);

CREATE INDEX MLOG_BTREE1 ON MATERIAL_LOG USING BTREE (
  ML_OLID_SRC,
  ML_LID
);

CREATE INDEX MLOG_BTREE2 ON MATERIAL_LOG USING BTREE (
  ML_OLID_DST,
  ML_LID
);

CREATE INDEX MLOG_BTREE3 ON MATERIAL_LOG USING BTREE (
  ML_OLID_SRC,
  ML_LID,
  ML_MTYPE
);

CREATE INDEX MLOG_BTREE4 ON MATERIAL_LOG USING BTREE (
  ML_OLID_DST,
  ML_LID,
  ML_MTYPE
);

CREATE INDEX MLOG_BRIN1 ON MATERIAL_LOG USING BRIN (
  ML_MLID
);

/* EQUIPMENT LOG */

CREATE TABLE EQUIPMENT_LOG (
  EL_ELID    INTEGER,
  EL_LID     INTEGER,
  EL_EID     INTEGER,
  EL_TS      TIMESTAMP,
  EL_SENSOR  VARCHAR(32),
  EL_READING INTEGER,
  PRIMARY KEY (EL_ELID, EL_LID)
);

CREATE INDEX EQLOG_BTREE01 ON EQUIPMENT_LOG USING BTREE (
  EL_LID,
  EL_EID,
  EL_TS,
  EL_SENSOR,
  EL_READING
);

CREATE INDEX EQLOG_BTREE02 ON EQUIPMENT_LOG USING BTREE (
  EL_LID,
  EL_EID,
  EL_TS
);

CREATE INDEX EQLOG_BRIN1 ON EQUIPMENT_LOG USING BRIN (
  EL_TS
);

CREATE INDEX EQLOG_BRIN2 ON EQUIPMENT_LOG USING BRIN (
  EL_ELID
);
